// Code generated by protoc-gen-go.
// source: ne.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	ne.proto

It has these top-level messages:
	Page
	User
	GetAllResponse
	LoginRequest
	LoginResponse
	RefreshRequest
	RefreshResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Page struct {
	Page    int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PerPage int64 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	Limit   int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  int64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto1.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Page) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Page) GetPerPage() int64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Page) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Page) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type User struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAllResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetAllResponse) Reset()                    { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()               {}
func (*GetAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAllResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type LoginRequest struct {
	Username     string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PasswordHash string `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	DeviceName   string `protobuf:"bytes,3,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	IsMobile     bool   `protobuf:"varint,4,opt,name=is_mobile,json=isMobile" json:"is_mobile,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto1.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *LoginRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *LoginRequest) GetIsMobile() bool {
	if m != nil {
		return m.IsMobile
	}
	return false
}

type LoginResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto1.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshRequest struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *RefreshRequest) Reset()                    { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string            { return proto1.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()               {}
func (*RefreshRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RefreshRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
}

func (m *RefreshResponse) Reset()                    { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string            { return proto1.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()               {}
func (*RefreshResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RefreshResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto1.RegisterType((*Page)(nil), "proto.Page")
	proto1.RegisterType((*User)(nil), "proto.User")
	proto1.RegisterType((*GetAllResponse)(nil), "proto.GetAllResponse")
	proto1.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto1.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto1.RegisterType((*RefreshRequest)(nil), "proto.RefreshRequest")
	proto1.RegisterType((*RefreshResponse)(nil), "proto.RefreshResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	StreamAll(ctx context.Context, in *Page, opts ...grpc.CallOption) (Users_StreamAllClient, error)
	GetAll(ctx context.Context, in *Page, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) StreamAll(ctx context.Context, in *Page, opts ...grpc.CallOption) (Users_StreamAllClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Users_serviceDesc.Streams[0], c.cc, "/proto.Users/StreamAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &usersStreamAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Users_StreamAllClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type usersStreamAllClient struct {
	grpc.ClientStream
}

func (x *usersStreamAllClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usersClient) GetAll(ctx context.Context, in *Page, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := grpc.Invoke(ctx, "/proto.Users/GetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	StreamAll(*Page, Users_StreamAllServer) error
	GetAll(context.Context, *Page) (*GetAllResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_StreamAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Page)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsersServer).StreamAll(m, &usersStreamAllServer{stream})
}

type Users_StreamAllServer interface {
	Send(*User) error
	grpc.ServerStream
}

type usersStreamAllServer struct {
	grpc.ServerStream
}

func (x *usersStreamAllServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _Users_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Users/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetAll(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _Users_GetAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAll",
			Handler:       _Users_StreamAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ne.proto",
}

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/proto.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := grpc.Invoke(ctx, "/proto.Auth/Refresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Auth_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ne.proto",
}

func init() { proto1.RegisterFile("ne.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x92, 0xb1, 0x72, 0xd3, 0x40,
	0x10, 0x86, 0x91, 0x6d, 0x39, 0xf2, 0xca, 0x36, 0xc3, 0x25, 0x64, 0x8c, 0x60, 0x86, 0x20, 0x9a,
	0x90, 0x22, 0x06, 0xa7, 0xa3, 0x61, 0x5c, 0x85, 0x82, 0x30, 0x8c, 0x80, 0x01, 0x2a, 0xcd, 0xc5,
	0x5e, 0x4b, 0x37, 0xc8, 0x3a, 0xa1, 0x3d, 0x87, 0x9e, 0x9e, 0x8a, 0x9e, 0x97, 0xe2, 0x15, 0x78,
	0x10, 0x46, 0x7b, 0x67, 0x8f, 0x45, 0x9d, 0xca, 0xb7, 0xff, 0xfd, 0xfe, 0xee, 0x5f, 0xed, 0x42,
	0x50, 0xe2, 0x79, 0x55, 0x6b, 0xa3, 0x85, 0xcf, 0x3f, 0xd1, 0xa3, 0x4c, 0xeb, 0xac, 0xc0, 0xa9,
	0xac, 0xd4, 0x54, 0x96, 0xa5, 0x36, 0xd2, 0x28, 0x5d, 0x92, 0x35, 0xc5, 0x0b, 0xe8, 0xbd, 0x93,
	0x19, 0x0a, 0x01, 0xbd, 0x4a, 0x66, 0x38, 0xf1, 0x4e, 0xbc, 0xd3, 0x6e, 0xc2, 0x67, 0xf1, 0x00,
	0x82, 0x0a, 0xeb, 0x94, 0xf5, 0x0e, 0xeb, 0x07, 0x15, 0xd6, 0x6c, 0x3f, 0x02, 0xbf, 0x50, 0x6b,
	0x65, 0x26, 0x5d, 0xd6, 0x6d, 0x21, 0x8e, 0xa1, 0xaf, 0x57, 0x2b, 0x42, 0x33, 0xe9, 0xb1, 0xec,
	0xaa, 0xf8, 0x0c, 0x7a, 0x1f, 0x09, 0x6b, 0x31, 0x86, 0x8e, 0x5a, 0xba, 0x27, 0x3a, 0x6a, 0xd9,
	0x3c, 0x5a, 0xca, 0xb5, 0x85, 0x0f, 0x12, 0x3e, 0xc7, 0x17, 0x30, 0xbe, 0x44, 0x33, 0x2f, 0x8a,
	0x04, 0xa9, 0xd2, 0x25, 0xa1, 0x78, 0x02, 0xfe, 0x86, 0xb0, 0xa6, 0x89, 0x77, 0xd2, 0x3d, 0x0d,
	0x67, 0xa1, 0x4d, 0x7e, 0xde, 0x10, 0x13, 0x7b, 0x13, 0xff, 0xf4, 0x60, 0xf8, 0x46, 0x67, 0xaa,
	0x4c, 0xf0, 0xdb, 0x06, 0xc9, 0x88, 0x08, 0x82, 0xe6, 0x86, 0xe9, 0x1e, 0xd3, 0x77, 0xb5, 0x78,
	0x0a, 0xa3, 0x4a, 0x12, 0x7d, 0xd7, 0xf5, 0x32, 0xcd, 0x25, 0xe5, 0xee, 0xf9, 0xe1, 0x56, 0x7c,
	0x2d, 0x29, 0x17, 0x8f, 0x21, 0x5c, 0xe2, 0x8d, 0x5a, 0x60, 0xca, 0x8c, 0x2e, 0x5b, 0xc0, 0x4a,
	0x6f, 0x1b, 0xca, 0x43, 0x18, 0x28, 0x4a, 0xd7, 0xfa, 0x5a, 0x15, 0xc8, 0xed, 0x06, 0x49, 0xa0,
	0xe8, 0x8a, 0xeb, 0xf8, 0x13, 0x8c, 0x5c, 0x9c, 0x5d, 0x0f, 0x43, 0xb9, 0x58, 0x20, 0x51, 0x6a,
	0xf4, 0x57, 0x2c, 0x5d, 0xa6, 0xd0, 0x6a, 0x1f, 0x1a, 0xa9, 0x89, 0x55, 0xe3, 0xaa, 0x46, 0xca,
	0x9d, 0xc7, 0xc5, 0x72, 0x22, 0x9b, 0xe2, 0xcf, 0x30, 0x4e, 0x6c, 0xbd, 0xed, 0xf4, 0xb6, 0xc8,
	0x5f, 0xe0, 0xee, 0x8e, 0x7c, 0xbb, 0xa1, 0x67, 0x04, 0x7e, 0x33, 0x2c, 0x12, 0xcf, 0x60, 0xf0,
	0xde, 0xd4, 0x28, 0xd7, 0xf3, 0xa2, 0x10, 0xdb, 0x39, 0x36, 0xfb, 0x14, 0xed, 0x0f, 0x35, 0xbe,
	0xf3, 0xdc, 0x13, 0xaf, 0xa0, 0x6f, 0xd7, 0xa0, 0xed, 0xbb, 0xef, 0x8a, 0xf6, 0x8a, 0xc4, 0xf7,
	0x7e, 0xfc, 0xf9, 0xfb, 0xab, 0x13, 0x8a, 0xc1, 0xf4, 0xe6, 0xc5, 0x94, 0x57, 0x62, 0xf6, 0xdb,
	0x83, 0xde, 0x7c, 0x63, 0x72, 0x71, 0x09, 0x3e, 0xcf, 0x42, 0x1c, 0xba, 0xff, 0xee, 0x2f, 0x4a,
	0x74, 0xd4, 0x16, 0x1d, 0xef, 0x90, 0x79, 0xa3, 0x38, 0x68, 0x78, 0x72, 0x63, 0xf2, 0x97, 0xde,
	0x99, 0xb8, 0x82, 0x03, 0xf7, 0x85, 0xc4, 0x36, 0x46, 0x7b, 0x16, 0xd1, 0xf1, 0xff, 0x72, 0x1b,
	0x17, 0xed, 0xe3, 0xae, 0xfb, 0xec, 0xbd, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x2b, 0xe8,
	0xe3, 0xb1, 0x03, 0x00, 0x00,
}
